version: "3.3"

services:
  mongo:
    image: mongo:6-focal
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qute
    networks:
      - qute

  mongo-express:
    image: mongo-express:1.0.0-alpha
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: qute
      ME_CONFIG_MONGODB_URL: mongodb://root:qute@mongo:27017/
    networks:
      - qute

networks:
  qute:
